#!/usr/bin/env python3
"""Bundle the modular host-plugin source under src/ into one readable plugin file.

pwnagotchi loads a SINGLE .py from custom-plugins/, but the source lives as
sibling modules under src/. This script inlines them into ink-cartridge.py.

Readability is a hard requirement: the file users copy onto their device must be
auditable plain Python, NOT a minified or base64-encoded blob. So every module's
source is embedded VERBATIM, separated by `#:IC-MODULE: <name>` sentinel lines.

Collision safety: three modules each define `make_handlers`, so a flat
concatenation would clobber. Instead, at import time the bundle reads its own
source, splits on the sentinels, and exec's each module chunk into its OWN
ModuleType registered in sys.modules under a private `_ic_<name>` prefix.
Intra-package imports are rewritten to the prefixed names, preserving the local
binding, so `telemetry.make_handlers` and `apps.AppsRuntime` resolve correctly.

The output is reproducible: same source -> byte-identical bundle. Anyone can
re-run `python3 build.py` and diff against the committed ink-cartridge.py to
verify it matches the source.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(HERE, "src")
OUT = os.path.join(HERE, "ink-cartridge.py")
# Update manifest the app fetches to detect an outdated on-device plugin and to
# verify the bytes it downloads. version + sha256 + bytes are auto-stamped from
# the built bundle; any other keys (e.g. "notes") are preserved across builds.
PLUGIN_JSON = os.path.join(HERE, "plugin.json")

# Dependency order. host_alias before apps (apps imports its helpers);
# registry before plugin; plugin last.
MODULES = ["registry", "host_alias", "telemetry", "apps", "controls", "proxy", "transport", "plugin"]
PREFIX = "_ic_"
SENTINEL = "#:IC-MODULE: "  # one per embedded module, at column 0 after a newline

HEADER = (
    "# Ink Cartridge — host plugin for pwnagotchi.\n"
    "# Copyright (C) 2026 Cristian Milea\n"
    "#\n"
    "# This program is free software: you can redistribute it and/or modify it\n"
    "# under the terms of the GNU General Public License as published by the Free\n"
    "# Software Foundation, either version 3 of the License, or (at your option)\n"
    "# any later version. This program is distributed WITHOUT ANY WARRANTY; see\n"
    "# the GNU General Public License for details: pwnagotchi-plugin/LICENSE.\n"
    "#\n"
    "# AUTO-GENERATED by build.py — DO NOT EDIT THIS FILE.\n"
    "# Edit pwnagotchi-plugin/src/*.py and run `python3 build.py` to regenerate.\n"
    "# pwnagotchi loads a single .py from custom-plugins/, so the modular source\n"
    "# is bundled here VERBATIM (readable, not encoded) — re-run build.py and diff\n"
    "# to verify this file matches src/.\n"
)

# Markers around the intra-package import shim in plugin.py.
MARK_START = "# === INTRA-PACKAGE IMPORTS (stripped by build.py) ==="
MARK_END = "# === END INTRA-PACKAGE IMPORTS ==="


def _rewrite_imports(src: str) -> str:
    """Rewrite intra-package imports to the prefixed module names, preserving
    the local binding name so module-qualified references keep working."""
    def _plain(m: re.Match) -> str:
        indent, name, asname = m.group(1), m.group(2), m.group(3)
        bind = asname if asname else name
        return f"{indent}import {PREFIX}{name} as {bind}"

    src = re.sub(
        r"^([ \t]*)import\s+(registry|host_alias|telemetry|apps|controls|proxy|transport)"
        r"(?:\s+as\s+(\w+))?[ \t]*$",
        _plain,
        src,
        flags=re.MULTILINE,
    )
    src = re.sub(
        r"^([ \t]*)from\s+(registry|host_alias|telemetry|apps|controls|proxy|transport)\s+import\b",
        lambda m: f"{m.group(1)}from {PREFIX}{m.group(2)} import",
        src,
        flags=re.MULTILINE,
    )
    return src


def _process_plugin_marker_block(src: str) -> str:
    """In plugin.py, drop the sys.path/os/sys shim lines inside the marker block
    (imports now resolve via sys.modules) but KEEP the rewritten sibling import
    lines. The marker comments themselves are dropped too."""
    lines = src.splitlines(keepends=True)
    out = []
    in_block = False
    for line in lines:
        if not in_block and MARK_START in line:
            in_block = True
            continue
        if in_block:
            if MARK_END in line:
                in_block = False
                continue
            stripped = line.strip()
            if (stripped.startswith("import os as _os")
                    or stripped.startswith("import sys as _sys")
                    or "_sys.path.insert" in stripped):
                continue
            out.append(line)
            continue
        out.append(line)
    return "".join(out)


def _module_source(name: str) -> str:
    src = open(os.path.join(SRC_DIR, name + ".py"), encoding="utf-8").read()
    if name == "plugin":
        src = _process_plugin_marker_block(src)
    src = _rewrite_imports(src)
    if SENTINEL in src:
        raise ValueError(f"{name}.py contains the reserved sentinel {SENTINEL!r}")
    if "'''" in src:
        raise ValueError(f"{name}.py contains ''' which breaks the readable bundle")
    return src


# The runtime loader prepended to the bundle. The embedded module source lives
# verbatim in a single raw triple-quoted string (_IC_SOURCE) below; this loader
# splits it on the sentinel lines and exec's each chunk into its own namespace,
# in dependency order. The sentinel literal is split across a concatenation so
# the loader's own text never matches the split pattern.
LOADER = '''import sys as _sys, types as _types


def _ic_load(text):
    """Split the embedded source on sentinel lines and exec each module chunk
    into its own namespace under a private name, in dependency order."""
    sentinel = "\\n#" + ":IC-MODULE: "
    for chunk in text.split(sentinel)[1:]:   # [0] is empty (text starts at \\n#)
        head, _, body = chunk.partition("\\n")
        name = head.strip()
        module = _types.ModuleType(name)
        module.__file__ = __file__
        _sys.modules[name] = module
        exec(compile(body, name, "exec"), module.__dict__)
'''

ENTRY = '''_ic_load(_IC_SOURCE)

# --- top-level entry symbols (pwnagotchi loader + smoke test) ---
InkCartridge = _sys.modules["_ic_plugin"].InkCartridge
build_registry = _sys.modules["_ic_plugin"].build_registry
AppsRuntime = _sys.modules["_ic_apps"].AppsRuntime
'''


def build_inline() -> str:
    embedded = []
    for name in MODULES:
        embedded.append(f"\n{SENTINEL}{PREFIX}{name}\n")
        embedded.append(_module_source(name))
    return (
        f"{HEADER}\n{LOADER}\n"
        f"_IC_SOURCE = r'''{''.join(embedded)}'''\n\n"
        f"{ENTRY}"
    )


def _artifact_passes_gate(path: str) -> bool:
    """Does the artifact import AND survive build_registry (the collision gate)
    in a fresh subprocess with the minimal pwnagotchi fakes?"""
    import subprocess
    import sys
    check = (
        "import importlib.util, sys, types\n"
        "for m in ('pwnagotchi','pwnagotchi.plugins','pwnagotchi.utils'):\n"
        "    sys.modules.setdefault(m, types.ModuleType(m))\n"
        "sys.modules['pwnagotchi.plugins'].Plugin = type('P',(),{})\n"
        "sys.modules['pwnagotchi'].utils = sys.modules['pwnagotchi.utils']\n"
        "sys.modules['pwnagotchi.utils'].total_unique_handshakes = lambda p: 0\n"
        f"spec = importlib.util.spec_from_file_location('ic_check', {path!r})\n"
        "mod = importlib.util.module_from_spec(spec)\n"
        "spec.loader.exec_module(mod)\n"
        "assert hasattr(mod, 'InkCartridge')\n"
        "reg = mod.build_registry(lambda: None, lambda: None, mod.AppsRuntime(),\n"
        "                         get_options=lambda: {}, toggle_plugin=lambda n, e: e)\n"
        "expected = {'status','pcap.get','game-over','state','manifest','ui',\n"
        "            'activate','deactivate','install','uninstall','push',\n"
        "            'reboot','shutdown','restart','plugin.toggle','plugin.update',\n"
        "            'display.png','plugins.list','stats.session',\n"
        "            'stats.os','stats.temp','stats.wifi'}\n"
        "assert {c for c in expected if reg.has(c)} == expected\n"
    )
    r = subprocess.run([sys.executable, "-c", check], capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stderr)
    return r.returncode == 0


def _plugin_version() -> str:
    """The single source of truth: PLUGIN_VERSION in src/plugin.py."""
    src = open(os.path.join(SRC_DIR, "plugin.py"), encoding="utf-8").read()
    m = re.search(r'^PLUGIN_VERSION\s*=\s*"([^"]+)"', src, flags=re.MULTILINE)
    if not m:
        raise SystemExit("PLUGIN_VERSION not found in src/plugin.py")
    return m.group(1)


def _stamp_from_bundle(bundle_bytes: bytes) -> dict:
    """The auto-stamped fields of plugin.json for a given bundle."""
    return {
        "version": _plugin_version(),
        "sha256": hashlib.sha256(bundle_bytes).hexdigest(),
        "bytes": len(bundle_bytes),
    }


def _read_plugin_json() -> dict:
    try:
        with open(PLUGIN_JSON, encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}


def _write_plugin_json(bundle_bytes: bytes) -> None:
    """Stamp version/sha256/bytes from the bundle, preserving any other keys."""
    data = _read_plugin_json()
    data.update(_stamp_from_bundle(bundle_bytes))
    with open(PLUGIN_JSON, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        f.write("\n")


def build() -> str:
    bundle = build_inline()
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(bundle)
    if not _artifact_passes_gate(OUT):
        raise SystemExit("build gate FAILED: bundle does not import cleanly")
    _write_plugin_json(bundle.encode("utf-8"))
    return OUT


def check() -> bool:
    """Return True iff the committed ink-cartridge.py and plugin.json are in
    sync with src/ (CI guard — no writes). Mirrors build_index.py --check."""
    fresh = build_inline()
    committed = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
    if fresh != committed:
        print("ink-cartridge.py is STALE — run `python3 build.py`")
        return False
    want = _stamp_from_bundle(fresh.encode("utf-8"))
    have = _read_plugin_json()
    drift = {k: (have.get(k), v) for k, v in want.items() if have.get(k) != v}
    if drift:
        print(f"plugin.json is STALE — run `python3 build.py` (drift: {drift})")
        return False
    return True


if __name__ == "__main__":
    if "--check" in sys.argv:
        raise SystemExit(0 if check() else 1)
    out = build()
    print(f"built {out} (readable, gate passed); stamped {os.path.basename(PLUGIN_JSON)}")
